# Generated by Django 5.2.8 on 2025-12-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_product_delete_clothes_delete_jewellery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelleryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ClothProduct',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.CharField(choices=[('cloth', 'Cloth'), ('jewellery', 'Jewellery')], max_length=20, null=True),
        ),
    ]
